### ISSUE TITLE
Create a maven multi module project as the top most project

### ISSUE THREAD

**Issue by chanakaudaya** [NGimhana/HC_ALERT#1]
Better to create a high level maven multi module project to wrap all the 4 projects.

**Comment by chanakaudaya** [comment]
@NGimhana please check

**Comment by NGimhana** [comment]
Update directory structure for EI artefacts.[Root directory](https://github.com/NGimhana/HC_ALERT/tree/master/WSO2%20Enterprise%20Integrator%20artefact/HealthcareNotificationPlatform)
